version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: facevault-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
