version: '3.9'

services:
  postgres:
    image: postgres:15.0
    container_name: facevault-pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: facevault
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
