# Stage 1: Build Angular app
FROM node:latest as build
WORKDIR /usr/local/app
COPY ./web ./

RUN npm install
RUN npx ng build

# Stage 2: Serve Angular app with NGINX
FROM nginx:latest
COPY --from=build /usr/local/app/dist/web/browser /usr/share/nginx/html
COPY ./web/config/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
