# Find all persons

GET http://localhost:8080/persons

### Get person data

GET http://localhost:8080/persons/64

### Create a new person

POST http://localhost:8080/persons
Content-Type: application/json

{
    "name": "Motoko",
    "cpf": "10000000010",
    "photoUrl": "https://avatars.githubusercontent.com/u/101954293?s=48&v=4"
}

### Update person data

PUT http://localhost:8080/persons/60
Content-Type: application/json

{
    "id": 60,
    "name": "Updated Name",
    "cpf": "00000000000",
    "photoUrl": "https://avatars.githubusercontent.com/u/101954293?s=48&v=4"
}

### Delete a person

DELETE http://localhost:8080/persons/60

### Find person by CPF

GET http://localhost:8080/persons/search/00000000000
